Upgrade to Spring Boot 2 and Spring Cloud Finchley (#39)
* Update to latest SNAPSHOT releases for Spring Boot and Cloud
* and enable Cloud Foundry deployment for core/deployables
* adjust JPA API accordingly and as necessary to make unit tests pass

* Pinch the finch
* several interim updates to get Grivet to build successfully with Boot 2.0 and Cloud Finchley, and Cloud Stream Elmhurst
* package import and Maven dependency updates
* disabled some Cloud auto-config
* hid Swagger endpoint behind profile b/c of springfox incompatibility w/ Boot 2.0
* pruned Redis output stream in persist module due to it being deprecated (unsupported)

* Actuator updates
* Restore actuator (production-ready) endpoints; @see https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.0.0-M4-Release-Notes#actuator-1
* Refine MetricsAspect impl to define pointcuts for each REST operation

* Bumping SNAPSHOT version to 0.4.0
* fixing compilation and classpath issues
* adding exclusion roles for auto-config based on issues w/ present boot 2.0 and cloud finchley integration state
* Removed io.dropwizard and readtalk dependencies; killed com.fns.grivet.monitoring package in common module
* Add io.micrometer dependencies for Prometheus support
* Re-plumbed existing controllers and datasource config to utilize MeterRegistry from io.micrometer

* Bumping versions of third-party dependencies

* Work in progress to support Docker Compose with Finchley
* Remove all traces of docker profile
* Fold in Eureka and Config Client settings to docker-compose YAML file variants
* Moved all individual application*.yml config to {application}.yml files https://github.com/fastnsilver/config-repo
* Prune all redundant config; global config (default profile) handled in application.yml in https://github.com/fastnsilver/config-repo
* Adjust startup, shutdown, status, and show-log scripts
* Docker Compose file service version updates and available heap memory increased for Java apps

* Temporarily disable SSL for MySQL datastore connections
* and enable batch rewrites (single insert statement multiple value rows)

* Miscellaneous updates
* Switch to fabric8 docker-maven-plugin
* Each deployable now has its own log4j2-spring.xml
* Version updates to third-party dependencies
* Disable config server client in test-resources module bootstrap.yml
* All datasources must have name attribute
* <groupId/> for hibernate-validator updated

* Upgrade to spring-cloud-starter-netflix dependencies
* Add hystrix
* Pull up dependencies into parent modules' POM files (i.e., deployables and support)

* Documentation updates

* 0.4.0 release prioritization

* Grivet has its own config repo now

* More config/dependency updates
* to keep up with Boot 2.0 and Cloud Finchley.BUILD-SNAPSHOT updates

* Config updates
* Boot and Finchley are starting to gel. Still a few auto-config issues to work through though, but integration has definitely improved since Sep-2017.

* Upgrade to Kay-RELEASE of Spring Data Release Train

* Some Spring Cloud Stream related fixes
* Still resulting in "Failed to start bean 'inputBindingLifecycle'; nested exception is java.lang.NoClassDefFoundError: org/apache/log4j/Logger"

* Get pipeline-mode working!
* Revert to Logback for logging, prune away all log4j2-spring.xml
* Remove Maven delombok profile
* All spring.application.name properties in bootstrap.yml are explicitly defined, rather than being property placeholders for project.artifactId
* Move <properties/> defined in sub-modules to parent POM
* Update maven-wrapper.properties to pull down latest Maven distribution
* Fix (de)/serialization issue with Op
* Use @StreamListener in PersistenceService; in combination with updates to spring.cloud.stream.bindings.input.consumer properties
* Update *.sql files to add partitions for 2 days before current date to all entityav_* tables
* Zuul gateway now starts up on port 9999

* Going forward

* Restore auto-config
* add @RefreshScope to enable refreshing config for certain controllers

* Update all tests to employ JUnit 5 API
* move bulk of test scope dependencies into test-resources module
* and upgrade a few third-party dependencies

* Upgrade wrapper to Maven 3.5.2

* Rename findByIdEntity method to findByEntityId
* and add tests to support JdbcEntityRepository implementation

* Remove redundant package definition
* occurrences of com.fns.grivet.model.Class.builder() can simply be referred to w/ Class.builder()

* Add Snyk badge

* Upgrade rest-assured to 3.0.5

* Revert rest-assured to 3.0.2

* Advise use of personal access token
* to obtain configuration from private Git repository
* also enable actuator endpoints on config server

* Temporarily disable auto-config
* Certain auto-config still not properly integrated with Cloud Finchley

* Revisions
* Update to micrometer 1.0.0-rc.5
* Re-enable Spring Cloud binder health and Hystrix

* Set milestone releases

* Remove boot-admin and microservices dashboard

* Upgrade to spring-mockmvc 3.0.6

* Update httpclient to 4.5.4

* Refine roadmap
* Most interesting and challenging will be the Reactive retread